version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.pass
    depends_on:
      - redis
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
  redis:
    image: redis
