version: "3.2"
services:
  web:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - 5000:5000
  redis:
    image: redis
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - web
    command: bash /ci/test.sh
